### ISSUE TITLE
Setting up database needs more details

### ISSUE THREAD

**Issue by chrisvire** [entando/entando-docs#1]
For `docs/src/main/asciidoc/installation/installation.adoc`:

1) The instructions  say "Create two databases" but doesn't say what names to use.  It should be something like:

Create two databases in your dbms.  The database names are strings composed like: 
```
<your-project-name>Port 
<your-project-name>Serv
```

2) The instructions should specify uncommenting the dependency on the mysql dependency if that database is used.

```
                    <dependency>
                            <groupId>mysql</groupId>
                            <artifactId>mysql-connector-java</artifactId>
                            <version>5.1.18</version>
                    </dependency>
 ```

**Comment by joewhite101** [comment]
Thanks @chrisvire 

@boatisEnt Can you take a look at adding these? Let me know if you have questions.

**Comment by joewhite101** [comment]
These items have been added to the documentation. Thanks for the ticket @chrisvire If you want you can also contribute directly to the documentation by forking this project and submitting pull requests 

https://github.com/entando/entando-docs
