### ISSUE TITLE
missing CRDAccessRole.yaml file in CRDs zip

### ISSUE THREAD

**Issue by joedugdale** [entando/entando-docs#18]
the documentation on http://docs.entando.com/ mentions there is a CRDAccessRole.yaml file, for creating a role that gets around having to set Cluster-Admin role for entando-controllers service account in Openshift
This file seems to be missing from the CRDs zip.

##############################
Grant cluster wide CRD read access only, and full access to Entando Custom resources. This requirement should not be a problem because there is no sensitive information in Entando’s custom resources.

oc create -f CRDAccessRole.yaml

**Comment by joewhite101** [comment]
Updated. Thanks for the note. If you see anything else don't hesitate to let us know.
