### ISSUE TITLE
Add host config tips/step to reach Entando app locally

### ISSUE THREAD

**Issue by avdev4j** [entando/entando-docs#187]
Hi there,
I have followed the starting guide (great job!) and I struggled a bit with the hosts config. Until I edited the hosts file I was not be able to reach the Entando login page in my Chrome browser.

I'm on MacOS, I'm not sure if this step is mandatory or if it's related to my configuration. Anyway, I wonder if it could be useful to add a new tips section or a new step to explain that (or maybe I missed something...).

Here an example of what the Host file should contains:

> 192.168.64.3 quickstart-entando.192.168.64.3.nip.io
> 192.168.64.3 quickstart-kc-entando.192.168.64.3.nip.io
> 192.168.64.3 quickstart-eci-entando.192.168.64.3.nip.io

Of course, you have to change the IP value with the one returned in the following command:
```
sudo kubectl get ingress -n entando -o jsonpath=\
'{.items[2].spec.rules[*].host}{.items[2].spec.rules[*].http.paths[2].path}{"\n"}'
```

What do you think?

**Comment by joewhite101** [comment]
Interesting. Haven't seen that one before. This is when running in multi-pass?

**Comment by joewhite101** [comment]
Also, does .nip.io work for you in general? We've seen a few cases where routers settings impact the functionality of the routing that .nip.io does. 

Do you have a google home instance connected to your router by chance? 

Might be worth adding your notes to the troubleshooting section for sure. @nshaw what do you think?

**Comment by nshaw** [comment]
@joewhite101 I just ran into a situation with another developer where they were using custom firmware on their router and it blocked nip.io requests. They could access nip.io in the browser but the domain resolution was failing, similar to this https://stackoverflow.com/questions/43834159/minishift-could-not-resolve-192-168-64-2-nip-io. 

@avdev4j We have a comment for users on Windows about some networking issues, linked from https://dev.entando.org/v6.2/docs/getting-started/#configure-access-to-your-cluster and pointing to the tips section here https://dev.entando.org/v6.2/tutorials/devops/local-tips-and-tricks.html#hyper-v-ip-changes.  What you wound up doing with the hosts file is effectively Option 1 in that list.  I can open a ticket on our side to rework the comments/tips to be a bit more general when people run into network issues.

Longer term, we're considering two changes which will help people get past these problems. One, we have a new (beta) Entando CLI which can help diagnose these problems and either automatically fix it or suggest solutions. Two, we have a story in the backlog to switch to a single domain for accessing an Entando installation and that should remove the need for nip.io altogether.

**Comment by avdev4j** [comment]
> Interesting. Haven't seen that one before. This is when running in multi-pass?

Yes, multi-pass, K3s, just like in the started guide .

> Also, does .nip.io work for you in general? We've seen a few cases where routers settings impact the functionality of the routing that .nip.io does.
Tbh, I've never used .nip.io before, so I can't tell you, sorry.

> Do you have a google home instance connected to your router by chance?
I've an Android box TV but I don't think i's could be consider like a Google home instance, isn't it?

The error displayed on Google Chrome is the following: `DNS_PROBE_FINISHED_NXDOMAIN`
I can't even know where it can come from. If you need me to do some tests, feel free to ask. 

Because there is a simple solution (and next features will fix that) I suggest to do like you said @nshaw just adapt the doc to something more generic.

**Comment by nshaw** [comment]
@avdev4j here's my take on this - https://github.com/entando/entando-docs/pull/189

**Comment by joewhite101** [comment]
Hey @avdev4j we merged and deployed a few changes that I think cover what you ran into. What do you think? Would they help somebody enough that ran into the same thing you did with DNS?

**Comment by avdev4j** [comment]
This sounds good for me. Great job @nshaw 

Thanks

**Comment by nshaw** [comment]
Thanks @avdev4j . If you have other suggestions or run into other issues please keep sharing them!
