### ISSUE TITLE
2.5 steps without cluster admin role (step 10)

### ISSUE THREAD

**Issue by joedugdale** [entando/entando-docs#19]
There's still a part requiring cluster admin role in the documentation under 2.5 - step 10, is there a way around this? Is the entando-operator role enough?

# Add the cluster-admin role to the default service account on entando-infra-namespace, required for k8s-service
oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:entando-infra-namespace:default

**Comment by joewhite101** [comment]
This is something we need to resolve from a documentation and clarity standpoint. The user isn't receiving actual cluster-level permissions in this case but we are giving them the ability to create resources using the entando apps resource definition. 

cc @ampie or @Kerruba to provide a bit more detail and the plans for clarifying this in the future. and @

**Comment by joewhite101** [comment]
OBE
