### ISSUE TITLE
Missing steps to deploy blueprint generated services/ui to the Entando 6 platform

### ISSUE THREAD

**Issue by tpatrizio** [entando/entando-docs#20]
The steps to build the first app with entando blueprint (https://es-entando.github.io/build-your-first-app) lacks a linkage with the deployment of the entando platform outline in the preceeding chapters of the doc. My understanding is that the Entando blueprint is used to generate services that act as plugins of the Entando platform, but I miss the steps to install those plugins into the platform, can you provide some hint in the documentation? The documentation is also missing an high level overview of the platform components that are deployed by the K8S Operator.

**Comment by joewhite101** [comment]
Hi @tpatrizio  

Yeah you are correct. We are working on updating the documentation for that now. I will send you a draft document via email later today that you can use to review.

In general the blueprint generates a service and a set of Micro Frontend widgets that are an Entando plugin. To install the plugin along with your entando app you build the service side to a docker image with:
`mvn clean complile jib:dockerBuild -Djib.to.image=<your image path>`

Where <your image path> is the name of the image repository you want to use. Then you can view and push your docker image to an image repository of your choice. Docker hub or an image repository in OpenShift for instance.

You can also build the React micro frontends that are generated from the blueprint using npm 
`npm install`
`npm build`

The output of the build directory can be uploaded to an Entando app via the app builder under `Configuration --> File Browser. Or if you are in an IDE can be added to the app in `src/main/webapp/resources/static/<whatever_you_want_for_mfs_structure>`

Then you can create the widget in Entando that will allow you to put it on a page:
In the app builder
1. In the top menu go to UX Patterns --> Widgets
2. Hit New (upper right)
3. In custom UI create the code to import the javascript for the widget (see below)

Here is an example of the javascript you can use to import the widget. You'll need to update for your paths:
```
<link rel="stylesheet" href="<@wp.resourceURL />survey/css/custom.css">
<script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script> 
<script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
<link href="<@wp.resourceURL />YOUR_PATH_/static/css/2.chunk.css" rel="stylesheet">
<link href="<@wp.resourceURL />YOUR_PATH_/static/css/main.chunk.css" rel="stylesheet"> 
<script src="<@wp.resourceURL />YOUR_PATH_/static/js/runtime~main.js"></script>  
<script src="<@wp.resourceURL />YOUR_PATH_/static/js/2.chunk.js"></script>
<script src="<@wp.resourceURL />YOUR_PATH_/static/js/main.chunk.js"></script>
<en-survey service-url="/survey" survey-id="${valueVar}"/>
```
The syntax for the widget CustomUI can be normal HTML or a freemarker template.


There are some other steps that we need to document relative to this process including using the Entando Operator to deploy your server side image and create the routing in kubernetes and in creating a bundle for the Digital Exchange. If you're ready for those as well ping me and we can get you that information.

**Comment by joewhite101** [comment]
This is resolved in updated documentation and instructions. Check out https://dev.entando.org for more details.
