### ISSUE TITLE
entando application in install-entando fails readiness probe

### ISSUE THREAD

**Issue by mjhost** [entando/entando-docs#24]
I'm trying to follow the steps at <https://es-entando.github.io/install-entando/#entando-application> but the health check on the application fail

```
Warning  Unhealthy  17m (x4 over 18m)      kubelet, m01       Readiness probe failed: Get http://172.17.0.12:8080/entando-de-app: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  3m37s (x146 over 18m)  kubelet, m01       Readiness probe failed: Get http://172.17.0.12:8083/digital-exchange/actuator/health: dial tcp 172.17.0.12:8083: connect: connection refused
```

it looks like de starts on the wrong port
```
2020-03-12 08:20:57.277  INFO 6 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8084 (http) with context path '/digital-exchange'
```
see attached relevant logs

[de.log](https://github.com/entando/entando-docs/files/4323266/de.log)
[server.log](https://github.com/entando/entando-docs/files/4323267/server.log)

**Comment by mjhost** [comment]
a workaround that lets the pod start is manual editing the deployment
`kubectl edit deployment test-entando-server-deployment -n test-namespace`
replacing the only 2 occurrences of 8083 with 8084

**Comment by joewhite101** [comment]
Resolved
