### ISSUE TITLE
Wrong repository mentioned in Clone and set up section

### ISSUE THREAD

**Issue by AngeloHulshout** [entando/entando-docs#3]
The Clone and Setup section suggests to clone common-components.git , this should be app-builder.git

**Comment by joewhite101** [comment]
This has been fixed in the docs and deployed. Thanks for the ticket @AngeloHulshout. Greatly appreciated.  If you want you can also contribute directly to the documentation by forking this project and submitting pull requests

https://github.com/entando/entando-docs

**Comment by AngeloHulshout** [comment]
@joewhite101 I will in future cases.

**Comment by AngeloHulshout** [comment]
@joewhite101 updated, but not yet published on docs.entando.com?

**Comment by joewhite101** [comment]
Hey @AngeloHulshout published now. Good catch. I missed a push.
