### ISSUE TITLE
Is this a mistake in AppBuilder or in the docs?

### ISSUE THREAD

**Issue by AngeloHulshout** [entando/entando-docs#4]
In the Mortgage app tutorial, the instructions read:

Assign the page model a code and a name. Codes represent the page model’s unique identifier. The name can be more human readable. For example:
Code: entando-page-purple
Name: Purple - BPM

When I do that, the Appbuilder reports an error:
Code 
Code contains invalid characters. Only alphanumeric characters and the underscore '_' are allowed.

Is this an oversight in the documentation, or is the AppBuilder to restrictive? In the former case, I'd be happy to fix it. @joewhite101

**Comment by AngeloHulshout** [comment]
I'll pick it up this week. @joewhite101

**Comment by joewhite101** [comment]
@AngeloHulshout done!

**Comment by AngeloHulshout** [comment]
Pull request created.

**Comment by joewhite101** [comment]
Merged. Thanks @AngeloHulshout. This will get deployed with the next set of changes. We have a few other things pending. Greatly appreciate the contributions.
