### ISSUE TITLE
Adding footer column in page

### ISSUE THREAD

**Issue by ritishbhardwaj** [entando/entando-docs#590]

**Comment by ritishbhardwaj** [comment]
@es-entando assign this issue to me

**Comment by nshaw** [comment]
@ritishbhardwaj could you please clarify the issue? And you can always submit a PR even if an issue is not already created. :)

**Comment by ritishbhardwaj** [comment]
Footer in the sense that i can create a column at the bottom of the webpage where we usually put all the resources of the company like 'careers', 'sources', 'link to news letter' , 'github, youtube, facebook links of web page owner', and etc.like that.
I hope that may be it is cleared now.

**Comment by nshaw** [comment]
@ritishbhardwaj A footer is usually either a shared web content you can place in a page or an HTML fragment you can include in a page template. See the tutorials here: https://developer.entando.com/v7.0/tutorials/compose/content-tutorial.html#create-content or https://developer.entando.com/v7.0/tutorials/compose/widgets-fragments.html.
