### ISSUE TITLE
Specific instructions for K3s, Rancher environments

### ISSUE THREAD

**Issue by Tudor44** [entando/entando-docs#722]
Hello,

in order to understand better how Entando's open platform works in a K3s environment.
Is it in plan a specific guide for install Entando on Rancher?

Thanks a lot.
Gaetano.

**Comment by nshaw** [comment]
Hi, @Tudor44 . We weren't planning on a specific guide for this use case, although it should be pretty close to our default guide - https://developer.entando.com/v7.1/docs/getting-started/. In a plain k8s setup (not k3s), you also need these settings just like in our other cloud install guides: 
```
                entando.requires.filesystem.group.override: "true"
    		entando.ingress.class: "nginx"

```
